# coding: utf-8

"""
    The Blue Alliance API v3

    # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.  # noqa: E501

    The version of the OpenAPI document: 3.5
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class APIStatusAppVersion(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'min_app_version': 'int',
        'latest_app_version': 'int'
    }

    attribute_map = {
        'min_app_version': 'min_app_version',
        'latest_app_version': 'latest_app_version'
    }

    def __init__(self, min_app_version=None, latest_app_version=None):  # noqa: E501
        """APIStatusAppVersion - a model defined in OpenAPI"""  # noqa: E501

        self._min_app_version = None
        self._latest_app_version = None
        self.discriminator = None

        self.min_app_version = min_app_version
        self.latest_app_version = latest_app_version

    @property
    def min_app_version(self):
        """Gets the min_app_version of this APIStatusAppVersion.  # noqa: E501

        Internal use - Minimum application version required to correctly connect and process data.  # noqa: E501

        :return: The min_app_version of this APIStatusAppVersion.  # noqa: E501
        :rtype: int
        """
        return self._min_app_version

    @min_app_version.setter
    def min_app_version(self, min_app_version):
        """Sets the min_app_version of this APIStatusAppVersion.

        Internal use - Minimum application version required to correctly connect and process data.  # noqa: E501

        :param min_app_version: The min_app_version of this APIStatusAppVersion.  # noqa: E501
        :type: int
        """
        if min_app_version is None:
            raise ValueError("Invalid value for `min_app_version`, must not be `None`")  # noqa: E501

        self._min_app_version = min_app_version

    @property
    def latest_app_version(self):
        """Gets the latest_app_version of this APIStatusAppVersion.  # noqa: E501

        Internal use - Latest application version available.  # noqa: E501

        :return: The latest_app_version of this APIStatusAppVersion.  # noqa: E501
        :rtype: int
        """
        return self._latest_app_version

    @latest_app_version.setter
    def latest_app_version(self, latest_app_version):
        """Sets the latest_app_version of this APIStatusAppVersion.

        Internal use - Latest application version available.  # noqa: E501

        :param latest_app_version: The latest_app_version of this APIStatusAppVersion.  # noqa: E501
        :type: int
        """
        if latest_app_version is None:
            raise ValueError("Invalid value for `latest_app_version`, must not be `None`")  # noqa: E501

        self._latest_app_version = latest_app_version

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, APIStatusAppVersion):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
