# coding: utf-8

"""
    The Blue Alliance API v3

    # Overview    Information and statistics about FIRST Robotics Competition teams and events.   # Authentication   All endpoints require an Auth Key to be passed in the header `X-TBA-Auth-Key`. If you do not have an auth key yet, you can obtain one from your [Account Page](/account).    A `User-Agent` header may need to be set to prevent a 403 Unauthorized error.  # noqa: E501

    The version of the OpenAPI document: 3.5
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class EventRankingSortOrderInfo(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'precision': 'int',
        'name': 'str'
    }

    attribute_map = {
        'precision': 'precision',
        'name': 'name'
    }

    def __init__(self, precision=None, name=None):  # noqa: E501
        """EventRankingSortOrderInfo - a model defined in OpenAPI"""  # noqa: E501

        self._precision = None
        self._name = None
        self.discriminator = None

        self.precision = precision
        self.name = name

    @property
    def precision(self):
        """Gets the precision of this EventRankingSortOrderInfo.  # noqa: E501

        Integer expressing the number of digits of precision in the number provided in `sort_orders`.  # noqa: E501

        :return: The precision of this EventRankingSortOrderInfo.  # noqa: E501
        :rtype: int
        """
        return self._precision

    @precision.setter
    def precision(self, precision):
        """Sets the precision of this EventRankingSortOrderInfo.

        Integer expressing the number of digits of precision in the number provided in `sort_orders`.  # noqa: E501

        :param precision: The precision of this EventRankingSortOrderInfo.  # noqa: E501
        :type: int
        """
        if precision is None:
            raise ValueError("Invalid value for `precision`, must not be `None`")  # noqa: E501

        self._precision = precision

    @property
    def name(self):
        """Gets the name of this EventRankingSortOrderInfo.  # noqa: E501

        Name of the field used in the `sort_order` array.  # noqa: E501

        :return: The name of this EventRankingSortOrderInfo.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EventRankingSortOrderInfo.

        Name of the field used in the `sort_order` array.  # noqa: E501

        :param name: The name of this EventRankingSortOrderInfo.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EventRankingSortOrderInfo):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
