//
// EliminationAllianceStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct EliminationAllianceStatus: Codable {

    public var playoffAverage: Double?
    public var level: String?
    public var record: WLTRecord?
    public var currentLevelRecord: WLTRecord?
    public var status: String?

    public init(playoffAverage: Double?, level: String?, record: WLTRecord?, currentLevelRecord: WLTRecord?, status: String?) {
        self.playoffAverage = playoffAverage
        self.level = level
        self.record = record
        self.currentLevelRecord = currentLevelRecord
        self.status = status
    }

    public enum CodingKeys: String, CodingKey { 
        case playoffAverage = "playoff_average"
        case level
        case record
        case currentLevelRecord = "current_level_record"
        case status
    }


}

