//
// MatchScoreBreakdown2019.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** See the 2019 FMS API documentation for a description of each value. https://frcevents2.docs.apiary.io/#reference/match-results/score-details */

public struct MatchScoreBreakdown2019: Codable {

    public var blue: MatchScoreBreakdown2019Alliance?
    public var red: MatchScoreBreakdown2019Alliance?

    public init(blue: MatchScoreBreakdown2019Alliance?, red: MatchScoreBreakdown2019Alliance?) {
        self.blue = blue
        self.red = red
    }


}

