//
// MatchScoreBreakdown2019Alliance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct MatchScoreBreakdown2019Alliance: Codable {

    public var adjustPoints: Int?
    public var autoPoints: Int?
    public var bay1: String?
    public var bay2: String?
    public var bay3: String?
    public var bay4: String?
    public var bay5: String?
    public var bay6: String?
    public var bay7: String?
    public var bay8: String?
    public var cargoPoints: Int?
    public var completeRocketRankingPoint: Bool?
    public var completedRocketFar: Bool?
    public var completedRocketNear: Bool?
    public var endgameRobot1: String?
    public var endgameRobot2: String?
    public var endgameRobot3: String?
    public var foulCount: Int?
    public var foulPoints: Int?
    public var habClimbPoints: Int?
    public var habDockingRankingPoint: Bool?
    public var habLineRobot1: String?
    public var habLineRobot2: String?
    public var habLineRobot3: String?
    public var hatchPanelPoints: Int?
    public var lowLeftRocketFar: String?
    public var lowLeftRocketNear: String?
    public var lowRightRocketFar: String?
    public var lowRightRocketNear: String?
    public var midLeftRocketFar: String?
    public var midLeftRocketNear: String?
    public var midRightRocketFar: String?
    public var midRightRocketNear: String?
    public var preMatchBay1: String?
    public var preMatchBay2: String?
    public var preMatchBay3: String?
    public var preMatchBay6: String?
    public var preMatchBay7: String?
    public var preMatchBay8: String?
    public var preMatchLevelRobot1: String?
    public var preMatchLevelRobot2: String?
    public var preMatchLevelRobot3: String?
    public var rp: Int?
    public var sandStormBonusPoints: Int?
    public var techFoulCount: Int?
    public var teleopPoints: Int?
    public var topLeftRocketFar: String?
    public var topLeftRocketNear: String?
    public var topRightRocketFar: String?
    public var topRightRocketNear: String?
    public var totalPoints: Int?

    public init(adjustPoints: Int?, autoPoints: Int?, bay1: String?, bay2: String?, bay3: String?, bay4: String?, bay5: String?, bay6: String?, bay7: String?, bay8: String?, cargoPoints: Int?, completeRocketRankingPoint: Bool?, completedRocketFar: Bool?, completedRocketNear: Bool?, endgameRobot1: String?, endgameRobot2: String?, endgameRobot3: String?, foulCount: Int?, foulPoints: Int?, habClimbPoints: Int?, habDockingRankingPoint: Bool?, habLineRobot1: String?, habLineRobot2: String?, habLineRobot3: String?, hatchPanelPoints: Int?, lowLeftRocketFar: String?, lowLeftRocketNear: String?, lowRightRocketFar: String?, lowRightRocketNear: String?, midLeftRocketFar: String?, midLeftRocketNear: String?, midRightRocketFar: String?, midRightRocketNear: String?, preMatchBay1: String?, preMatchBay2: String?, preMatchBay3: String?, preMatchBay6: String?, preMatchBay7: String?, preMatchBay8: String?, preMatchLevelRobot1: String?, preMatchLevelRobot2: String?, preMatchLevelRobot3: String?, rp: Int?, sandStormBonusPoints: Int?, techFoulCount: Int?, teleopPoints: Int?, topLeftRocketFar: String?, topLeftRocketNear: String?, topRightRocketFar: String?, topRightRocketNear: String?, totalPoints: Int?) {
        self.adjustPoints = adjustPoints
        self.autoPoints = autoPoints
        self.bay1 = bay1
        self.bay2 = bay2
        self.bay3 = bay3
        self.bay4 = bay4
        self.bay5 = bay5
        self.bay6 = bay6
        self.bay7 = bay7
        self.bay8 = bay8
        self.cargoPoints = cargoPoints
        self.completeRocketRankingPoint = completeRocketRankingPoint
        self.completedRocketFar = completedRocketFar
        self.completedRocketNear = completedRocketNear
        self.endgameRobot1 = endgameRobot1
        self.endgameRobot2 = endgameRobot2
        self.endgameRobot3 = endgameRobot3
        self.foulCount = foulCount
        self.foulPoints = foulPoints
        self.habClimbPoints = habClimbPoints
        self.habDockingRankingPoint = habDockingRankingPoint
        self.habLineRobot1 = habLineRobot1
        self.habLineRobot2 = habLineRobot2
        self.habLineRobot3 = habLineRobot3
        self.hatchPanelPoints = hatchPanelPoints
        self.lowLeftRocketFar = lowLeftRocketFar
        self.lowLeftRocketNear = lowLeftRocketNear
        self.lowRightRocketFar = lowRightRocketFar
        self.lowRightRocketNear = lowRightRocketNear
        self.midLeftRocketFar = midLeftRocketFar
        self.midLeftRocketNear = midLeftRocketNear
        self.midRightRocketFar = midRightRocketFar
        self.midRightRocketNear = midRightRocketNear
        self.preMatchBay1 = preMatchBay1
        self.preMatchBay2 = preMatchBay2
        self.preMatchBay3 = preMatchBay3
        self.preMatchBay6 = preMatchBay6
        self.preMatchBay7 = preMatchBay7
        self.preMatchBay8 = preMatchBay8
        self.preMatchLevelRobot1 = preMatchLevelRobot1
        self.preMatchLevelRobot2 = preMatchLevelRobot2
        self.preMatchLevelRobot3 = preMatchLevelRobot3
        self.rp = rp
        self.sandStormBonusPoints = sandStormBonusPoints
        self.techFoulCount = techFoulCount
        self.teleopPoints = teleopPoints
        self.topLeftRocketFar = topLeftRocketFar
        self.topLeftRocketNear = topLeftRocketNear
        self.topRightRocketFar = topRightRocketFar
        self.topRightRocketNear = topRightRocketNear
        self.totalPoints = totalPoints
    }


}

