//
// MatchScoreBreakdown2016.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** See the 2016 FMS API documentation for a description of each value. */

public struct MatchScoreBreakdown2016: Codable {

    public var blue: MatchScoreBreakdown2016Alliance?
    public var red: MatchScoreBreakdown2016Alliance?

    public init(blue: MatchScoreBreakdown2016Alliance?, red: MatchScoreBreakdown2016Alliance?) {
        self.blue = blue
        self.red = red
    }


}

