//
// MatchScoreBreakdown2017.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** See the 2017 FMS API documentation for a description of each value. */

public struct MatchScoreBreakdown2017: Codable {

    public var blue: MatchScoreBreakdown2017Alliance?
    public var red: MatchScoreBreakdown2017Alliance?

    public init(blue: MatchScoreBreakdown2017Alliance?, red: MatchScoreBreakdown2017Alliance?) {
        self.blue = blue
        self.red = red
    }


}

