//
// TeamEventStatusRank.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct TeamEventStatusRank: Codable {

    /** Number of teams ranked. */
    public var numTeams: Int?
    public var ranking: TeamEventStatusRankRanking?
    /** Ordered list of names corresponding to the elements of the &#x60;sort_orders&#x60; array. */
    public var sortOrderInfo: [TeamEventStatusRankSortOrderInfo]?
    public var status: String?

    public init(numTeams: Int?, ranking: TeamEventStatusRankRanking?, sortOrderInfo: [TeamEventStatusRankSortOrderInfo]?, status: String?) {
        self.numTeams = numTeams
        self.ranking = ranking
        self.sortOrderInfo = sortOrderInfo
        self.status = status
    }

    public enum CodingKeys: String, CodingKey { 
        case numTeams = "num_teams"
        case ranking
        case sortOrderInfo = "sort_order_info"
        case status
    }


}

