//
// TeamEventStatusAlliance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct TeamEventStatusAlliance: Codable {

    /** Alliance name, may be null. */
    public var name: String?
    /** Alliance number. */
    public var number: Int
    public var backup: TeamEventStatusAllianceBackup?
    /** Order the team was picked in the alliance from 0-2, with 0 being alliance captain. */
    public var pick: Int

    public init(name: String?, number: Int, backup: TeamEventStatusAllianceBackup?, pick: Int) {
        self.name = name
        self.number = number
        self.backup = backup
        self.pick = pick
    }


}

