//
// TeamEventStatusPlayoff.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Playoff status for this team, may be null if the team did not make playoffs, or playoffs have not begun. */

public struct TeamEventStatusPlayoff: Codable {

    public enum Level: String, Codable {
        case qm = "qm"
        case ef = "ef"
        case qf = "qf"
        case sf = "sf"
        case f = "f"
    }
    public enum Status: String, Codable {
        case won = "won"
        case eliminated = "eliminated"
        case playing = "playing"
    }
    /** The highest playoff level the team reached. */
    public var level: Level?
    public var currentLevelRecord: WLTRecord?
    public var record: WLTRecord?
    /** Current competition status for the playoffs. */
    public var status: Status?
    /** The average match score during playoffs. Year specific. May be null if not relevant for a given year. */
    public var playoffAverage: Int?

    public init(level: Level?, currentLevelRecord: WLTRecord?, record: WLTRecord?, status: Status?, playoffAverage: Int?) {
        self.level = level
        self.currentLevelRecord = currentLevelRecord
        self.record = record
        self.status = status
        self.playoffAverage = playoffAverage
    }

    public enum CodingKeys: String, CodingKey { 
        case level
        case currentLevelRecord = "current_level_record"
        case record
        case status
        case playoffAverage = "playoff_average"
    }


}

